cc_library(
    name = "test",  # Label: //main:test
    srcs = ["test.cpp"], # input source file
    hdrs = ["test.h"], # related headers
    visibility = ["//visibility:public"] # using this header at the other packages
)